name: release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        outputs:
            published: ${{ steps.semantic-release.outputs.published }}
            docker-image: ${{ steps.prep.outputs.docker-image }}:${{ github.sha }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3.3.0

            - name: Semantic release
              id: semantic-release
              uses: ahmadnassri/action-semantic-release@v2.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Repo metadata
              if: steps.semantic-release.outputs.published == 'true'
              id: repo
              uses: actions/github-script@v6.3.3
              with:
                  script: |
                      const repo = await github.rest.repos.get(context.repo)
                      return repo.data

            - name: Prepare
              if: steps.semantic-release.outputs.published == 'true'
              id: prep
              run: |
                  echo "docker-image=ghcr.io/${{ github.event.repository.full_name }}" >> $GITHUB_OUTPUT

            - name: Set up Docker Buildx
              if: steps.semantic-release.outputs.published == 'true'
              id: buildx
              uses: docker/setup-buildx-action@v2.2.1
              with:
                  version: latest

            - name: Login to ghcr.io
              if: steps.semantic-release.outputs.published == 'true'
              uses: docker/login-action@v2.1.0
              with:
                  registry: ghcr.io
                  # TODO: make username a secret too
                  username: kakious
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              if: steps.semantic-release.outputs.published == 'true'
              id: docker-build
              uses: docker/build-push-action@v3.2.0
              with:
                  push: true
                  builder: ${{ steps.buildx.outputs.name }}
                  context: .
                  tags: |
                      ${{ steps.prep.outputs.docker-image }}:${{ github.ref_name }}
                      ${{ steps.prep.outputs.docker-image }}:${{ github.sha }}
                      ${{ steps.prep.outputs.docker-image }}:${{ steps.semantic-release.outputs.release-version }}
                  labels: |
                      org.opencontainers.image.title=${{ fromJson(steps.repo.outputs.result).name }}
                      org.opencontainers.image.description=${{ fromJson(steps.repo.outputs.result).description }}
                      org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
                      org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
                      org.opencontainers.image.revision=${{ github.sha }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
